name: "Expressions"
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug mode"
        required: true
        default: false
        type: boolean
      fail:
        description: "Forces fail"
        required: true
        default: false
        type: boolean
env:
  WORKFLOW_VAR: "This is a workflow variable"
  OVERWRITTEN: "Another workflow variable"

jobs:
  debug-check:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "THIS IS A JOB VARIABLE"
      OVERWRITTEN: "This is an overwritten variable"
    steps:
      - name: "Print Debug Info"
        if: inputs.debug 
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}" 
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"       

      - name: "Debug triggered from main"
        if: inputs.debug && github.ref == 'refs/heads/main'
        run: |
          echo "Triggered from main branch!"
      - name: "Print Job Variables"
        env:
          STEP_VAR: "Step level variable"
        run: |
          echo "Step var: ${{ env.STEP_VAR }}"
          echo "Job var: ${{ env.JOB_VAR }}" 
          echo "Workflow var: ${{ env.WORKFLOW_VAR }}" 
          echo "Overwritten: ${{ env.OVERWRITTEN }}"
  
  functions-pr-data:
    runs-on: ubuntu-latest
    steps:
      - name: "Print PR labels"
        if: github.event_name == 'pull_request'
        run: |
          cat << EOF
          ${{ toJSON(github.event.pull_request.labels) }}
          EOF
      - name: "Bug check"
        if: contains(toJSON(github.event.pull_request.labels.*.name), 'fix')
        run: |
          echo "This PR is a bug fix"
      
      - name: "Sleep and Cancel"
        run: |
          echo "This job will be cancelled"  
          sleep 20
      - name: "Failing step"
        if: inputs.fail
        run: |
          echo "This step forces to fail"
          exit 1   
          
      - name: "Conditional Step - Failure"
        if: failure()
        run: |
          echo "This step runs only if a previous step failed"
      
      - name: "Print Always"
        if: always()
        run: |
          echo "This step always runs"

      - name: "On Cancel"
        if: cancelled()
        run: |
          echo "Workflow has been cancelled"
      
        

